Updated to new autostart mechanism

diff --git a/rc_dot_local b/rc_dot_local
--- a/rc_dot_local
+++ b/rc_dot_local
@@ -1,5 +1,30 @@
-/usr/bin/touch /tmp/ohgee.out
-/bin/mv /tmp/ohgee.out /tmp/last-ohgee.out
-/usr/bin/touch /tmp/ohgee.out
-/bin/chmod 777 /tmp/ohgee.out
-su - pi -c "cd Documents/workspace/ohgee;pwd;./autorun.sh" > /tmp/ohgee.out 2>&1
+#!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# Print the IP address
+_IP=$(hostname -I) || true
+if [ "$_IP" ]; then
+  printf "My IP address is %s\n" "$_IP"
+fi
+/sbin/swapoff -a
+
+/usr/bin/touch /var/log/ohgee.out
+set clobber
+/bin/mv /var/log/ohgee.out /var/log/last-ohgee.out
+
+/usr/bin/touch /var/log/ohgee.out
+/bin/chmod 777 /var/log/ohgee.out
+# move to LXDE-pi/autostart
+# su - pi -c "cd Documents/workspace/ohgee;pwd;./autorun.sh" > /var/log/ohgee.out 2>&1
+
+exit 0
